/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Point { 
    from?: number;
    to?: number;
    AVG_DURATION?: number;
    MIN_DURATION?: number;
    MAX_DURATION?: number;
    COUNT?: number;
    THROUGHPUT?: number;
    ELEMENTS_PER_SECOND?: number;
    ERRORS?: number;
    ERRORS_PER_SECOND?: number;
    ERROR_RATE?: number;
    AVG_TTFB?: number;
    MIN_TTFB?: number;
    MAX_TTFB?: number;
}