/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Sla { 
    status?: Sla.StatusEnum;
}
export namespace Sla {
    export type StatusEnum = 'PASSED' | 'WARNING' | 'FAILED' | 'NO SLA';
    export const StatusEnum = {
        PASSED: 'PASSED' as StatusEnum,
        WARNING: 'WARNING' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum,
        NOSLA: 'NO SLA' as StatusEnum
    };
}