/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SLAElementDefinition { 
    /**
     * Unique identifier of the element.
     */
    elementID?: string;
    /**
     * Name of the element.
     */
    name?: string;
    category?: SLAElementDefinition.CategoryEnum;
    /**
     * The name of the user path in which the element is.
     */
    userPath?: string;
    /**
     * The parent name of the element.
     */
    parent?: string;
}
export namespace SLAElementDefinition {
    export type CategoryEnum = 'TRANSACTION' | 'PAGE' | 'REQUEST';
    export const CategoryEnum = {
        TRANSACTION: 'TRANSACTION' as CategoryEnum,
        PAGE: 'PAGE' as CategoryEnum,
        REQUEST: 'REQUEST' as CategoryEnum
    };
}