/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestUpdateRequest { 
    /**
     * Name of the test.
     */
    name?: string;
    /**
     * Description of the test.
     */
    description?: string;
    /**
     * Quality status of the test.
     */
    qualityStatus?: TestUpdateRequest.QualityStatusEnum;
}
export namespace TestUpdateRequest {
    export type QualityStatusEnum = 'PASSED' | 'FAILED';
    export const QualityStatusEnum = {
        PASSED: 'PASSED' as QualityStatusEnum,
        FAILED: 'FAILED' as QualityStatusEnum
    };
}