/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestStatistics { 
    /**
     * Total number of requests in the scenario that did not encounter any error.
     */
    totalRequestCountSuccess?: number;
    /**
     * Total number of requests in the scenario that encountered errors.
     */
    totalRequestCountFailure?: number;
    /**
     * Average time in seconds for all requests of the scenario to be performed (from first byte sent to last byte received).
     */
    totalRequestDurationAverage?: number;
    /**
     * Total number of requests in the scenario that are performed per second.
     */
    totalRequestCountPerSecond?: number;
    /**
     * Total number of the scenario Transactions executed without encountering any error.
     */
    totalTransactionCountSuccess?: number;
    /**
     * Total number of the scenario Transactions executed with errors.
     */
    totalTransactionCountFailure?: number;
    /**
     * Average time in seconds for all Transactions of the scenario to be executed.
     */
    totalTransactionDurationAverage?: number;
    /**
     * Total number of the scenario Transactions executed per second.
     */
    totalTransactionCountPerSecond?: number;
    /**
     * Total number of times when the 'Actions' Container was run for each Virtual User without encountering any error.
     */
    totalIterationCountSuccess?: number;
    /**
     * Total number of times when the 'Actions' Container was run for each Virtual User and encountered an error.
     */
    totalIterationCountFailure?: number;
    /**
     * Total size of http traffic received in bytes.
     */
    totalGlobalDownloadedBytes?: number;
    /**
     * Average size of http traffic received in bytes per second.
     */
    totalGlobalDownloadedBytesPerSecond?: number;
    totalGlobalCountFailure?: number;
    /**
     * Last value received for the number of requests in the scenario that are performed per second.
     */
    lastRequestCountPerSecond?: number;
    /**
     * Last value received for the average time in milliseconds for all Transactions of the scenario.
     */
    lastTransactionDurationAverage?: number;
    /**
     * Last value received for the total number of Virtual Users executed in the test.
     */
    lastVirtualUserCount?: number;
}