/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ThresholdDefinition { 
    /**
     * The operator of threshold definition
     */
    operator?: ThresholdDefinition.OperatorEnum;
    /**
     * The value of threshold definition
     */
    value?: number;
}
export namespace ThresholdDefinition {
    export type OperatorEnum = '>=' | '<=' | '==';
    export const OperatorEnum = {
        GreaterThanOrEqualTo: '>=' as OperatorEnum,
        LessThanOrEqualTo: '<=' as OperatorEnum,
        : '==' as OperatorEnum
    };
}