/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ElementDefinition { 
    /**
     * Unique identifier of the element.
     */
    id?: string;
    /**
     * Name of the element.
     */
    name?: string;
    /**
     * Full path of the element including the element itself.
     */
    path?: Array<string>;
    /**
     * Type of the element.
     */
    type?: string;
}