/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of the event
 */
export type EventType = 'ERROR' | 'SLA' | 'ALERT';

export const EventType = {
    ERROR: 'ERROR' as EventType,
    SLA: 'SLA' as EventType,
    ALERT: 'ALERT' as EventType
};