/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AsCodeFile } from './asCodeFile';
import { ScenarioDefinition } from './scenarioDefinition';


export interface ProjectDefinition { 
    /**
     * Neoload Project Id.
     */
    projectId?: string;
    /**
     * Neoload Project name.
     */
    projectName?: string;
    /**
     * Neoload Project version.
     */
    projectVersion?: string;
    asCodeFiles?: Array<AsCodeFile>;
    scenarios?: Array<ScenarioDefinition>;
}