/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ScenarioDefinition { 
    /**
     * Scenario name.
     */
    scenarioName?: string;
    /**
     * Duration (in seconds) of the scenario.
     */
    scenarioDuration?: number;
    /**
     * Total Virtual User number of the scenario. Return 0 if the Virtual User number is not determined.
     */
    scenarioVUs?: number;
    /**
     * The scenarion location. Can be a yaml file or NLP path.
     */
    scenarioSource?: string;
}