/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { SLAKPIDefinition } from './sLAKPIDefinition';
import { SLAStatusDefinition } from './sLAStatusDefinition';
import { SLAValueDefinition } from './sLAValueDefinition';
import { ThresholdDefinition } from './thresholdDefinition';


export interface SLAGlobalIndicatorDefinition { 
    kpi?: SLAKPIDefinition;
    status?: SLAStatusDefinition;
    value?: SLAValueDefinition;
    warningThreshold?: ThresholdDefinition;
    failedThreshold?: ThresholdDefinition;
}