/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { SLAElementDefinition } from './sLAElementDefinition';
import { SLAKPIDefinition } from './sLAKPIDefinition';
import { SLAStatusDefinition } from './sLAStatusDefinition';
import { ThresholdDefinition } from './thresholdDefinition';


export interface SLAPerIntervalDefinition { 
    kpi?: SLAKPIDefinition;
    status?: SLAStatusDefinition;
    /**
     * Percentage of intervals warning
     */
    warning?: number;
    warningThreshold?: ThresholdDefinition;
    /**
     * Percentage of intervals failed
     */
    failed?: number;
    failedThreshold?: ThresholdDefinition;
    element?: SLAElementDefinition;
}