/**
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Status of the SLA
 */
export type SLAStatusDefinition = 'PASSED' | 'WARNING' | 'FAILED';

export const SLAStatusDefinition = {
    PASSED: 'PASSED' as SLAStatusDefinition,
    WARNING: 'WARNING' as SLAStatusDefinition,
    FAILED: 'FAILED' as SLAStatusDefinition
};